on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      run: |
        touch ~/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/id_rsa
        chmod 600 ~/id_rsa
        ssh-keygen -R ${{ secrets.SSH_HOST }}
    - name: connect and pull
      run: ssh -i ~/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} " exit"
    - name: cleanup
      run: rm -rf ~/.ssh