on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/ssh-key-2022-04-03
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ssh-key-2022-04-03
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/ssh-key-2022-04-03.pub
        cat ssh-key-2022-04-03.pub >> ~/.ssh/authorized_keys
    - name: connect and pull
      run: ssh -i ~/.ssh/ssh-key-2022-04-03 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} " exit"
    - name: cleanup
      run: rm -rf ~/.ssh