on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      run: |
        mkdir ~/.ssh
        touch ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        echo "Host server" >> ~/.ssh/config
        echo "  HostName ${{ secrets.SSH_HOST }}" >> ~/.ssh/config
        echo "  User ${{ secrets.SSH_USER }}" >> ~/.ssh/config
        echo "  AddKeysToAgent yes" >> ~/.ssh/config
        echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
    - name: connect and pull
      run: ssh server " exit"
    - name: cleanup
      run: rm -rf ~/.ssh