on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      uses: shimataro/ssh-key-action@v2
      with:
        key: {%- raw -%} ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }}{% endraw%} >> ~/.ssh/known_hosts
    - name: connect and pull
      # run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} " exit"
      run : ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "exit"
    - name: cleanup
      run: rm -rf ~/.ssh